# -*- coding: utf-8 -*-
"""juego adivina el animal con 3 versiones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qoWR7Mmsqw2eRs37cKS_yTc91mab-ob
"""

import random #para eventos aleatorios, es una libreria siempre van arriba
numero = random.randint(0, 2) # se elije un numero al azar. es una función.




print("Adivina adivinador, que animal tenemos de visita hoy")
print("")
inicio = input("En cada pista tendra la posibilidad de descifrar el animal.\nRecuerde que solo tendrás una oportunidad. \nSi no esta seguro de responder solo debe pulsar <enter> para continuar con las pistas ")
print("")
 #presentación del juego

pistas_tortuga = [#tortuga
         "Pista 1: Soy un animal que pertenece a los vertebrados, lo que significa que tengo columna vertebral.",
         "Pista 2: Mi cuerpo está cubierto por una capa dura, pero no tengo pelo ni plumas.",
         "Pista 3: Soy un animal de sangre fría, y pongo huevos con una cáscara dura que entierro para que se incuben."]
#se llama arreglo

pistas_raton = [ #ratón
       "Pista 1: Soy pequeño, de orejas grandes y me muevo muy rápido.",
       "Pista 2: Me gusta roer y muchas veces vivo en casas o campos.",
      "Pista 3: Soy protagonista de muchos cuentos e historietas, como el famoso Mickey."]


pistas_panda = [ #panda
       "Pista 1:  Vivo en las montañas de China y soy un símbolo de conservación.",
       "Pista 2: Paso la mayor parte del día comiendo bambú.",
       "Pista 3: Soy blanco y negro, y parezco un oso de peluche gigante."]

pista_todas = [pistas_tortuga,pistas_raton,pistas_panda]

respuestas_todas = ["tortuga", "ratón", "panda"]

acertado = False



respuesta_correcta = respuestas_todas[numero]
pistas = pista_todas[numero]


print("\nPrimera pista:")


for i in range(0, len(pistas)):
  #for i comienza el bucle
  #pista, para que se vaya recorriedo la lista de pistas
  #se empieza a presentar a partir de la 2da pista

    print(pistas[i])  # Muestra la primera pista directamente
    print("")

    entrada = input(f"Intento:  ").strip().lower()
    print("")



    if entrada == respuesta_correcta:

        print(f"¡Correcto! Lo adivinaste con {i+1} pistas.\n")
        acertado = True
        break #se termina el bucle


    elif not entrada == "":
        print("Incorrecto. Fin del juego.\n")
        break



# Si no acertó en el bucle, última oportunidad
if not acertado and i == len(pistas)-1:
    ultima_respuesta = input("Última oportunidad, ¿quién soy? ").strip().lower()
    if ultima_respuesta == respuesta_correcta:
        print("¡Correcto! Era soy un "+respuesta_correcta+".\n")
        acertado = True

    else:
        print("Incorrecto")



if not acertado:
   input("presiona x para leer la solución")
   print("La solución es "+respuesta_correcta+".")



input("")